# Generated by Django 6.0.3 on 2026-03-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('queixa', models.CharField(choices=[('D', 'Depressao'), ('A', 'Ansiedade')], max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
